# Generated by Django 2.2.7 on 2019-12-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fontapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='phone',
            field=models.CharField(max_length=120),
        ),
    ]
